### PR TITLE
Add fvgq test

### PR DESCRIPTION
**Pull request by wupeifan**

### CODE REVIEW

**Comment by jlperla** [comment]
Thanks @wupeifan

**Comment by cpfiffer** [comment]
Looks like the solutions are off here. We should probably (a) widen the tolerance bounds to something like 

```julia
all(isapprox.(sol.A, ..., atol=0.1))
```

Perhaps even wider than `atol=0.1`, since some of the comparisons seem quite off.

**Comment by wupeifan** [comment]
@cpfiffer Those solutions are different, due to some unknown bug. The solution I posted is "correct" as they are compared to Dynare ones already.

**Comment by cpfiffer** [comment]
Sure, but the fact is that the test values do not match the Dynare numbers. If this is 

1. A bug, then we have an issue -- these answers should be more or less exact (I think?)
2. Numerical errors, no real issue, just need wider bounds.

**Comment by wupeifan** [comment]
Those are not numerical errors. They just don't match. @cpfiffer

**Comment by wupeifan** [comment]
Merge?

**Pull request merged**
