### PR TITLE
Add second order p cache

### PR DESCRIPTION
**Pull request by wupeifan**
This is to add most of the reused objects into the cache of the second-order derivatives.

### CODE REVIEW

**Comment by wupeifan** [comment]
Should be good for now

**Review by cpfiffer — APPROVED** [review]
Looks solid to me!

**Comment by wupeifan** [comment]
Yeah I know: all the tests are fine, and I rewrote several lines of algebra.
But I am not satisfied with the benchmarks as it only improved a little.

**Comment by wupeifan** [comment]
I'm happy with the above change. Not done yet.

**Pull request merged**
